<?php

/**
 * @file
 * Copyright 2019 Google Inc.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
 * License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

/**
 * @file
 * Module file for Apigee Edge: API Docs.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function apigee_api_catalog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the apigee_api_catalog module.
    case 'help.page.apigee_api_catalog':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display documentation of your APIs to your developers using OpenAPI documentation.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function apigee_api_catalog_page_attachments(array &$attachments) {
  // Add base tag for SmartDocs Angular application.
  $xuacompatible = [
    '#tag' => 'base',
    '#attributes' => [
      'href' => '/',
    ],
  ];
  $attachments['#attached']['html_head'][] = [$xuacompatible, 'base-href'];

  // Add script to fix issue with SmartDocs Angular app.
  $attachments['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => '(window as any).global = window; ',
      '#attributes' => ['src' => ''],
      '#weight' => -1,

    ],
    // Key to make it possible to recognize this HTML element when altering.
    'apigee-smartdocs',
  ];
}
